### ISSUE TITLE
CNN Türk çalışmıyor... 🙃

### ISSUE THREAD

**Issue by abdullah-erturk** [keyiflerolsun/IPTV_YenirMi#250]
Liste için teşekkür ederim.

CNN Türk çalışmıyor...

**Comment by keyiflerolsun** [comment]
![Screenshot_2024-12-19-04-35-38-680_com lagradost cloudstream3 prerelease](https://github.com/user-attachments/assets/8755dddf-2f7b-4317-be5b-5e3e02ce70da)
