### ISSUE TITLE
cnbce

### ISSUE THREAD

**Issue by Missinginch** [keyiflerolsun/IPTV_YenirMi#67]
Selam. cnbce yayınını eklemeniz mümkün mü?
https://www.cnbce.com/canli-yayin

**Comment by ramazansancar** [comment]
@keyiflerolsun Kontrol ediyorum

**Comment by ramazansancar** [comment]
Şu anlık youtube yayını eklenebiliyor. (Onda da ekran resmindeki yayın var :/)
Youtube için PR: https://github.com/keyiflerolsun/IPTV_YenirMi/pull/68
![image](https://github.com/user-attachments/assets/f55a34cf-04fe-4ec8-935f-26d937dcbe18)

Diğeri için ythls 'ye bir api eklenmesi gerekiyor. Onu da @keyiflerolsun halledebilir :(

Curl isteği bu şekilde gelen cevaptan `source` apide response'a yazılması gerekiyor.
```curl
curl --location --request POST 'https://www.cnbce.com/api/live-stream/source' \
--header 'origin: https://www.cnbce.com'
```
